// Generated by gencpp from file puzzlebot_controller/MoveFeedback.msg
// DO NOT EDIT!


#ifndef PUZZLEBOT_CONTROLLER_MESSAGE_MOVEFEEDBACK_H
#define PUZZLEBOT_CONTROLLER_MESSAGE_MOVEFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace puzzlebot_controller
{
template <class ContainerAllocator>
struct MoveFeedback_
{
  typedef MoveFeedback_<ContainerAllocator> Type;

  MoveFeedback_()
    : distance_to_target(0.0)
    , angle_to_target(0.0)  {
    }
  MoveFeedback_(const ContainerAllocator& _alloc)
    : distance_to_target(0.0)
    , angle_to_target(0.0)  {
  (void)_alloc;
    }



   typedef double _distance_to_target_type;
  _distance_to_target_type distance_to_target;

   typedef double _angle_to_target_type;
  _angle_to_target_type angle_to_target;





  typedef boost::shared_ptr< ::puzzlebot_controller::MoveFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::puzzlebot_controller::MoveFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct MoveFeedback_

typedef ::puzzlebot_controller::MoveFeedback_<std::allocator<void> > MoveFeedback;

typedef boost::shared_ptr< ::puzzlebot_controller::MoveFeedback > MoveFeedbackPtr;
typedef boost::shared_ptr< ::puzzlebot_controller::MoveFeedback const> MoveFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::puzzlebot_controller::MoveFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::puzzlebot_controller::MoveFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::puzzlebot_controller::MoveFeedback_<ContainerAllocator1> & lhs, const ::puzzlebot_controller::MoveFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.distance_to_target == rhs.distance_to_target &&
    lhs.angle_to_target == rhs.angle_to_target;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::puzzlebot_controller::MoveFeedback_<ContainerAllocator1> & lhs, const ::puzzlebot_controller::MoveFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace puzzlebot_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::puzzlebot_controller::MoveFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::puzzlebot_controller::MoveFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::puzzlebot_controller::MoveFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::puzzlebot_controller::MoveFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::puzzlebot_controller::MoveFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::puzzlebot_controller::MoveFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::puzzlebot_controller::MoveFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b73dc5583aad0d7c99117ecba4b8f6df";
  }

  static const char* value(const ::puzzlebot_controller::MoveFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb73dc5583aad0d7cULL;
  static const uint64_t static_value2 = 0x99117ecba4b8f6dfULL;
};

template<class ContainerAllocator>
struct DataType< ::puzzlebot_controller::MoveFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "puzzlebot_controller/MoveFeedback";
  }

  static const char* value(const ::puzzlebot_controller::MoveFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::puzzlebot_controller::MoveFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Feedback\n"
"float64 distance_to_target\n"
"float64 angle_to_target\n"
;
  }

  static const char* value(const ::puzzlebot_controller::MoveFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::puzzlebot_controller::MoveFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.distance_to_target);
      stream.next(m.angle_to_target);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::puzzlebot_controller::MoveFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::puzzlebot_controller::MoveFeedback_<ContainerAllocator>& v)
  {
    s << indent << "distance_to_target: ";
    Printer<double>::stream(s, indent + "  ", v.distance_to_target);
    s << indent << "angle_to_target: ";
    Printer<double>::stream(s, indent + "  ", v.angle_to_target);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PUZZLEBOT_CONTROLLER_MESSAGE_MOVEFEEDBACK_H
