// Auto-generated. Do not edit!

// (in-package puzzlebot_controller.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class MoveFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.distance_to_target = null;
      this.angle_to_target = null;
    }
    else {
      if (initObj.hasOwnProperty('distance_to_target')) {
        this.distance_to_target = initObj.distance_to_target
      }
      else {
        this.distance_to_target = 0.0;
      }
      if (initObj.hasOwnProperty('angle_to_target')) {
        this.angle_to_target = initObj.angle_to_target
      }
      else {
        this.angle_to_target = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type MoveFeedback
    // Serialize message field [distance_to_target]
    bufferOffset = _serializer.float64(obj.distance_to_target, buffer, bufferOffset);
    // Serialize message field [angle_to_target]
    bufferOffset = _serializer.float64(obj.angle_to_target, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type MoveFeedback
    let len;
    let data = new MoveFeedback(null);
    // Deserialize message field [distance_to_target]
    data.distance_to_target = _deserializer.float64(buffer, bufferOffset);
    // Deserialize message field [angle_to_target]
    data.angle_to_target = _deserializer.float64(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 16;
  }

  static datatype() {
    // Returns string type for a message object
    return 'puzzlebot_controller/MoveFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'b73dc5583aad0d7c99117ecba4b8f6df';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Feedback
    float64 distance_to_target
    float64 angle_to_target
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new MoveFeedback(null);
    if (msg.distance_to_target !== undefined) {
      resolved.distance_to_target = msg.distance_to_target;
    }
    else {
      resolved.distance_to_target = 0.0
    }

    if (msg.angle_to_target !== undefined) {
      resolved.angle_to_target = msg.angle_to_target;
    }
    else {
      resolved.angle_to_target = 0.0
    }

    return resolved;
    }
};

module.exports = MoveFeedback;
